language: bash

sudo: required

services:
- docker


script:
    - for script in *.sh ; do docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/"${script}" ; done
    - bash template.sh -o option -a argument
